import {
  ArrowRight,
  BadgeCheck,
  Baby,
  BarChart3,
  BellRing,
  Briefcase,
  CalendarDays,
  ChefHat,
  Circle,
  ClipboardList,
  Clock3,
  HardHat,
  Home,
  Leaf,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MessageSquare,
  Package,
  Phone,
  Plus,
  Search,
  Send,
  Shield,
  Sparkles,
  Star,
  Trash2,
  User,
  Users,
  Wallet,
  Wrench,
  Zap,
  X,
  EllipsisVertical,
} from "lucide-react";

const ICONS = {
  arrowRight: ArrowRight,
  badgeCheck: BadgeCheck,
  baby: Baby,
  barChart: BarChart3,
  bell: BellRing,
  briefcase: Briefcase,
  calendar: CalendarDays,
  chefHat: ChefHat,
  clipboard: ClipboardList,
  clock: Clock3,
  hardHat: HardHat,
  home: Home,
  leaf: Leaf,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  mapPin: MapPin,
  message: MessageSquare,
  package: Package,
  phone: Phone,
  plus: Plus,
  search: Search,
  send: Send,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  trash: Trash2,
  user: User,
  users: Users,
  wallet: Wallet,
  wrench: Wrench,
  x: X,
  zap: Zap,
  more: EllipsisVertical,
};

const AppIcon = ({ name, size = 18, className = "", strokeWidth = 2 }) => {
  const Icon = ICONS[name] || Circle;
  return <Icon size={size} className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
};

export default AppIcon;
